server:
  port: 8093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.229.129
  rabbitmq:
    host: 192.168.229.129
    virtual-host: /wsm
    username: wsm
    password: wsmwsm
gmall:
  jwt:
    pubKeyPath: F:\\ideadevelop\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
